# Generated by Django 3.1 on 2023-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
